config = {'train_data_path':['../dataset/subset0/',
                             '../dataset/subset1/',
                             '../dataset/subset2/',
                             '../dataset/subset3/',
                             '../dataset/subset4/',
                             '../dataset/subset5/',
                             '../dataset/subset6/',
                             '../dataset/subset7/',
                             '../dataset/subset8/'],
          'val_data_path':['../dataset/subset9/'],
          'test_data_path':['../dataset/subset9/'],
          
          'train_preprocess_result_path':'../result/train_preprocess_result_path', # contains numpy for the data and label, which is generated by prepare.py
          'val_preprocess_result_path':'../result/val_preprocess_result_path',  # make sure copy all the numpy into one folder after prepare.py
          'test_preprocess_result_path':'../result/test_preprocess_result_path',
          
          'train_annos_path':'D:\lungnoduledetection\dataset\CSVFILES/annotations.csv',
          'val_annos_path':'D:\lungnoduledetection\dataset\CSVFILES/annotations.csv',
          'test_annos_path':'D:\lungnoduledetection\dataset\CSVFILES/annotations.csv',

          'black_list':[],
          
          'preprocessing_backend':'python',

          'luna_segment':'../dataset/seg-lungs-LUNA16/', # download from https://luna16.grand-challenge.org/data/
          'preprocess_result_path':'../result/preprocess_result_path',
          'luna_data':'../dataset/',
          'luna_label':'../dataset/CSVFILES/annotations.csv'
         } 
